### ISSUE TITLE
Erweiterung des Menüs in der Sidebar: Anzeige der jüngsten Plugins

### ISSUE THREAD

**Issue by croser1** [studip/PluginMarket#44]
1. Zeigt der Marktplatz eine rote Zahl an und klicke ich darauf, sehe ich das jüngste oder die jüngsten Plugins. klicke ich weg, sind sie weg. Ich würde mir die jüngsten aber gerne noch einmal in Ruhe anschauen. Dafür wäre eine Erweiterung gut: Die Anzeige der jüngsten Plugins (jüngst könnte heißen: das Datum, an dem das letzte Upload erfolgt ist) - analog zu den letzten Forenbeiträgen im Forum.
2. Habe ich statt Kacheln die Listenansicht angeschaut, sehe ich nach Klick auf das Marktplatz-Icon mit der roten Zahl keine neuen Plugins. Evtl. könnten in der Liste alle neuen Plugins ein rotes Sternchen erhalten? 
   Grundsätzlich hilft aber auch in diesem Fall mir das unter 1. Geschriebene.
3. könnte in der Listenansicht auch noch helfen: Anzeige des letzten Upload-Datums.

**Comment by Krassmus** [comment]
Zumindest die sechs neusten Plugins werden im Marktplatz angezeigt.
