### ISSUE TITLE
Neueste Plugins Filter

### ISSUE THREAD

**Issue by nimuelle** [studip/PluginMarket#51]
Wenn man zb. sieht, dass es 3 neue Plugins auf dem Marktplatz gibt und auf ein Plugin klickt. Anschließend möchte man die anderen 2 neuen Plugins sehen, leider gibt es keine Infos mehr, welche das noch waren.

Eine Idee wäre, dass man die "letzten 5 " als Filter in der Sidebar anbietet.

**Comment by Krassmus** [comment]
Hau rein!

**Comment by tleilax** [comment]
Mit #53 gefixt.
