### ISSUE TITLE
Plugin Updates funktionieren nicht / Problem mit dem Pluginnamen

### ISSUE THREAD

**Issue by noackorama** [studip/PluginMarket#72]
In dem generierten XML steht im Moment der Name aus der DB, der beim Einstellen des Plugins vergeben wird. Das ist aber häufig ein "schöner" Name und nicht der, der auch im manifest der zip Datei steht. Damit werden die Updates nicht erkannt. Man könnte den Namen einfach aus dem zip auslesen, hier ergibt sich aber das Problem, dass man dann unter einem Plugin Eintrag im Marktplatz verschiedene Plugins hochladen könnte. Man könnte also einfach ein fremdes Plugin, von dem man weiss dass es häufig benutzt wird, kapern und so bösartigen Code einschmuggeln.

Vorschlag:

- der vorhandene Name wird der "displayname", den gibts mittlerweile ja auch im manifest
- zusätzlich muss man den internen pluginname eingeben
- wenn man ein release hinzufügt wird überprüft, ob der pluginname aus dem zip mit dem bereits hinterlegten übereinstimmt

**Comment by ssuchi** [comment]
Aus Sicherheitsgründen müsste der interne Pluginname dann ein Pflichtfeld und eindeutig sein bei der Eingabe eines Plugins im Marktplatz, oder?
