### ISSUE TITLE
Man kann das Webhook secret nicht löschen

### ISSUE THREAD

**Issue by Krassmus** [studip/PluginMarket#73]
Wenn man einen Webhook mit secret eingerichtet hat, kann man diesen nicht mehr später wieder löschen.

**Comment by Krassmus** [comment]
Scheint kein Fehler im Plugin sondern in SORM zu sein, dass null-Einträge beim store nicht gespeichert werden.

**Comment by noackorama** [comment]
Hm, funktioniert doch :)
