### ISSUE TITLE
Pluginmarktplatz meldet verfügbares Update auf nicht existierende Pluginversion

### ISSUE THREAD

**Issue by s-at-dq** [studip/PluginMarket#86]
Beim ESemesterApparatePlugin wird im Stud.IP-System ein Update auf Version 1.0 angeboten, obwohl diese Version nicht im Pluginmarktplatz existiert.

Es sieht so aus, als liefert der Pluginmarktplatz falsche Versionsangaben zum Plugin.

**Comment by Krassmus** [comment]
In https://develop.studip.de/studip/plugins.php/pluginmarket/extern/xml stehen die Versionen korrekt drin.

**Comment by s-at-dq** [comment]
Es war ein Sprachproblem: Derjenige, der mir die Meldung weitergab, meinte ein Update auf Migration 1.
